### ISSUE TITLE
didn't receive the gps location with this code

### ISSUE THREAD

**Issue by henanzhong** [ameltech/sme-se868-a-library#2]
hello, I have tested the code "localizationInfo" for the "smarteverything", inside which has a gps module, se868as.
But the result was always "locking for GPS...", I don't know what is the problem? So i want to ask for help here if it is possible.
Have u ever met this problem? Thanks before.

**Comment by smkkHw** [comment]
Did U tried outside in an completed open air situation?

Because that GPS has an internal antenna is it better to test it outside in a sunny day.
Just to eliminate any possible noise.

Mik

**Comment by henanzhong** [comment]
No, we didn't try outside, but just close to the windows. I will try that after. Thanks.
Is it possible caused by the problem of configuration or problem of the gps module?

**Comment by smkkHw** [comment]
The configuration (if not changed by You) is the default one, and works in most of the cases, maybe the totality of case :) 

Before say that is the gps module that has som eproblem.... please try in a sunny day aoutside.

Mik

**Comment by henanzhong** [comment]
Yeah, you are right. I will try in a sunny day outside. 

You really helped me, thinks a lot !

Nanzhong

**Comment by searobin** [comment]
Item solved
