### ISSUE TITLE
GPS not working

### ISSUE THREAD

**Issue by MansourM61** [ameltech/sme-se868-a-library#8]
Hi,
I have a SmartEverything Fox board. All the examples and libraries shipped with the board are working fine except for GPS and SigFox.

When I upload "LocanizationInfo" example, the GPS module won't get into ready state and in the serial monitor I only see "Locking GPS position...". (Basically the code "smeGps.ready()" always returns False).

I tried outdoor in clear sky with no building around, but the problem didn't get solved.

Please let me know if I can deal with this issue.

Cheers.

**Comment by searobin** [comment]
The gps module should lock enough satellites, in open sky within 30/60 seconds.
The library has not been changed recently.
Could you please have another try?

Where are you located?

**Comment by MansourM61** [comment]
I tried it for almost 2 minutes. I am in Glasgow, Scotland.

**Comment by searobin** [comment]
Just another question, 

We haven't received any real issue on the GPS functionality so far,
I'm wondering if your GPS module is properly working.

Which is the mounted GPS module type? Is it the 868-A? 
 Could you please have another try, maybe with clear sky (no clouds if possible).
Better, at this point, if with another board.

Thanks

Severino

**Comment by smkkHw** [comment]
Another question.

which core did U download for the ASME ?

From the Board manager (after the Arduino Zero core) U should download the ARROW core

Mik

**Comment by MansourM61** [comment]
Thank you both for replying.

searobin: The GPS chip is SE868-AS. I have two SmartEverything Fox Boards and both have the same issue.

smkkHw: I followed the PDF file [http://docs-europe.electrocomponents.com/webdocs/144b/0900766b8144b09d.pdf](url).
It doesn't say any thing about ARROW core. Maybe that's the problem. Could you please tell me which core I should pick from "Board Manager"?

Cheers.

**Comment by searobin** [comment]
Mansour.

Looking for Smarteverything in the board manager you will find two board libraries: Amel-Tech and Arrow.

You need to install the second one

Ciao

Severino

⁣--

Severino Peirano
Via Colzani 48 -I-20831 Seregno MB
seve@ioteam.it
+39 340 6745795​

Il giorno 15 set 2017, 13:39, alle ore 13:39, MansourM61 <notifications@github.com> ha scritto:

**Comment by MansourM61** [comment]
Thanks a lot searobin and smkkHw.
You saved my day.
I installed the cores you suggested and GPS is working like a charm. SigFox module is also working fine.
It looks like I had the wrong core installed.
Cheers.

**Comment by smkkHw** [comment]
U R welcome and happy coding with ASME
